config/routes.rb
FishAlbum::Application.routes.draw do
  get  "admin/index"
  get  "admin/login"
  get  "admin/logout"

  resources :families do
    resources :fish
  end
  resources :fish do
    resources :photos
  end
  resources :photos
  resource :search

  # Facebook access
  scope "/fb" do
    resources :families do
      resources :fish
    end
    resources :fish do
      resources :photos
    end
    resources :photos
    resource :search
  end

  match "/admin/" => "admin#login"
  root to: "families#index"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :fish

  mount_uploader :file, PhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  # GET /photos
  # GET /photos.json
  def index
    if params[:fish_id]
      @fish = Fish.find(params[:fish_id])
      @photos = Photo.joins(:fish => :family ).where(fish_id: params[:fish_id]).order('families.name_jp, fish.name_jp')
    else
      @fish = nil
      @photos = Photo.joins(:fish => :family).order('families.name_jp, fish.name_jp')
    end

    respond_to do |format|
      if admin?
        format.html
      else
        format.html {render layout: 'mobile', template: 'photos/index.mobile' }
      end
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    if params[:fish_id]
      @fish = Fish.find(params[:fish_id])
    else
      @fish = nil
    end
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if admin?
        format.html
      else
        format.html {render layout: 'mobile.fullscreen', template: 'photos/show.mobile' }
      end
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    if params[:fish_id]
      @fish = Fish.find(params[:fish_id])
    else
      @fish = nil
    end
    @photo = Photo.new
    @photo.fish = @fish

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    if params[:fish_id]
      @fish = Fish.find(params[:fish_id])
    else
      @fish = nil
    end
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_path(@photo), notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        @photo.file.recreate_versions!
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])

    if @photo.fish
      @fish = @photo.fish
    else
      @fish = nil
    end

    @photo.remove_file!
    @photo.destroy

    respond_to do |format|
      if @fish
        format.html { redirect_to fish_photos_path(@fish) }
      else
        format.html { redirect_to photos_path }
      end
      format.json { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
-if @photo.errors.any?
  #error_explanation
    %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
    %ul
      - @photo.errors.full_messages.each do |msg|
        %li= msg

= image_tag(@photo.file.mobile.url) if @photo.file?
= form_for(@photo) do |f|
  .field
    %table
      %tr
        %td= f.label '魚'
        %td
          = f.grouped_collection_select(:fish_id, Family.all, :fish, :name_jp, :id, :name_jp)
          = link_to '[科を追加する]', new_family_path
          = link_to '[魚を追加する]', new_fish_path
      %tr
        %td= f.label 'URL'      
        %td
          = f.text_field :remote_file_url
          = link_to '[Picasaを開く]', 'https://picasaweb.google.com/101680618216862629937', target: '_blank'
      %tr
        %td= f.label 'ファイル'
        %td= f.file_field :file
    %p ※URLまたはファイルのどちらかを入力してください
    = f.hidden_field :file_cache
  .action
    = f.submit '保存'

app/views/photos/edit.html.haml
- if @photo.fish
  %h1 #{@photo.fish.name_jp}の写真編集
- else
  %h1 写真編集

= render 'form'

%hr
- if @photo.fish
  %button= link_to '同じ魚の写真一覧', fish_photos_path(@photo)
%button= link_to '写真一覧', photos_path
%button= link_to '表示', @photo
%button= link_to '削除', @photo, :confirm => 'まじでまじすか？', :method => :delete

app/views/photos/index.html.haml
= content_for :header do
  - if @fish
    %h1= "#{@fish.name_jp}の写真一覧"
    .menu
      %button= link_to "#{@fish.name_jp}の写真を追加", new_fish_photo_path(@fish)
      %button= link_to "#{@fish.name_jp}の情報を編集", edit_fish_path(@fish)
  - else
    %h1 写真一覧
    .menu
      %button= link_to '写真を追加', new_photo_path

%table
  %tr
    %th 科
    %th 魚
    %th 学名
    %th 英名
    %th ID
    %th.photo 写真
    %th サイズ
    %th.operation 操作
  - @photos.each do |photo|
    %tr
      %td
        -  if photo.fish and photo.fish.family
          =link_to photo.fish.family.name_jp, family_fish_index_path(photo.fish.family)
      %td
        - if photo.fish
          =link_to photo.fish.name_jp, fish_photos_path(photo.fish)
      %td= photo.fish.name_la if photo.fish
      %td= photo.fish.name_en if photo.fish
      %td= photo.id
      %td.photo= image_tag(photo.file.thumb.url)
      %td= photo.file.get_geometry
      %td
        - if @fish
          %button= link_to '表示', [@fish, photo]
          %button= link_to '編集', edit_fish_photo_path(@fish, photo)
          %button= link_to '削除', [@fish, photo], confirm: 'まじですか？', method: :delete
        - else
          %button= link_to '表示', photo
          %button= link_to '編集', edit_photo_path(photo)
          %button= link_to '削除', photo, confirm: 'まじですか？', method: :delete

app/views/photos/index.mobile.html.haml
= content_for :header do
  %h1
    - if @fish
      = "#{@fish.name_jp}"
    - else
      Photos
%p= @fish.description_jp if @fish
/.ui-grid-a
/  - @photos.each do |photo|
/    %div{'class' => cycle('ui-block-a', 'ui-block-b')}
/      = link_to image_tag(photo.file.mobile.url), photo

%center
  - @photos.each do |photo|
    = link_to image_tag(photo.file.mobile.url), photo

app/views/photos/new.html.haml
= content_for :header do
  - if @photo.fish
    %h1
      - if @photo.fish.family
        = "#{@photo.fish.family.name_jp}の#{@photo.fish.name_jp}の写真を追加"
      - else
        = "#{@photo.fish.name_jp}の写真を追加"
  - else
    %h1 写真追加
= render 'form'

app/views/photos/show.html.haml
= content_for :header do
  %div{"data-role" => "header"}
    - if @photo.fish
      %h1 #{@photo.fish.name_jp}
    - else
      %h1 Photo
  .menu    
    %button= link_to '編集', edit_photo_path(@photo)
    %button= link_to '削除', @photo, :confirm => 'まじでまじすか？', :method => :delete
    - if @photo.fish
      %button= link_to "#{@photo.fish.name_jp}の写真一覧", fish_photos_path(@photo.fish)
      %button= link_to "#{@photo.fish.name_jp}の写真追加", new_fish_photo_path(@photo.fish)

%hr
%div.center
  = image_tag(@photo.file_url) if @photo.file?
%hr

app/views/photos/show.mobile.html.haml
= content_for :header do
  - if @photo.fish
    %h1= "#{@photo.fish.name_jp}/#{@photo.fish.name_en}"
  - else
    %h1 Photo
= image_tag @photo.file.mobile.url, 'class' => 'mobile_center'