config/routes.rb
FishAlbum::Application.routes.draw do
  get  "admin/index"
  get  "admin/login"
  get  "admin/logout"

  resources :families do
    resources :fish
  end
  resources :fish do
    resources :photos
  end
  resources :photos
  resource :search

  # Facebook access
  scope "/fb" do
    resources :families do
      resources :fish
    end
    resources :fish do
      resources :photos
    end
    resources :photos
    resource :search
  end

  match "/admin/" => "admin#login"
  root to: "families#index"
end

app/views/layouts/_navbar.html.haml
%div{'data-role' => 'navbar'}
  %ul
    %li= link_to 'Families', families_path,   'data-role' => 'button'
    %li= link_to 'Fish'    , fish_index_path, 'data-role' => 'button'
    %li= link_to 'Photos'  , photos_path,     'data-role' => 'button'
    %li= link_to 'Search'  , search_path,     'data-role' => 'button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fish Album-管理画面
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      - if notice
        %div#notice
          %p= notice
      %ul#navbar
        - if admin?
          %li= link_to '科一覧', families_path
          %li= link_to '魚一覧', fish_index_path
          %li= link_to '写真一覧', photos_path
          %li= link_to '検索', search_path
          %li= link_to 'モバイル画面', admin_logout_path, { 'class' => 'highlight' }
        - else
          %li= link_to '管理画面', admin_login_path
      = yield :header
    %article
      = yield
    %footer
      %p
        2011 Copyright (C) by D.S.Murai and Y.C.
        = link_to '[Issues]', 'https://github.com/ychubachi/fish_album/issues', target: '_blank'

app/views/layouts/mobile.fullscreen.html.haml
!!!
%html
  %head
    %title Fish Album
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
      %link{:href => "http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css", :rel => "stylesheet"}/
      %script{:src => "http://code.jquery.com/jquery-1.6.4.min.js", :type => "text/javascript"}
      %script{:src => "http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js", :type => "text/javascript"}

  %body
    %div{"data-role" => "page", 'data-add-back-btn' => 'true', 'data-fullscreen' => 'true'}
      %div{"data-role" => "header", 'data-position' => 'fixed'}
        = yield :header
        = render 'layouts/navbar'
      %div{"data-role" => "content"}
        = yield
      %div{"data-role" => "footer", 'data-position' => 'fixed'}
        %h4 2011 (C) by D.S.Murai & YC

app/views/layouts/mobile.html.haml
!!!
%html
  %head
    %title Fish Album
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
      %link{:href => "http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css", :rel => "stylesheet"}/
      %script{:src => "http://code.jquery.com/jquery-1.6.4.min.js", :type => "text/javascript"}
      %script{:src => "http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js", :type => "text/javascript"}
      = stylesheet_link_tag 'mobile'
  %body
    %div{"data-role" => "page", 'data-add-back-btn' => 'true', |
    'data-theme' => 'a', 'data-content-theme' => 'a'}
      %div{"data-role" => "header"}
        = yield :header
        = render 'layouts/navbar'
      %div{"data-role" => "content"}
        = yield
      %div{"data-role" => "footer"}
        %h4 2011 (C) by D.S.Murai & YC