config/routes.rb
FishAlbum::Application.routes.draw do
  get  "admin/index"
  get  "admin/login"
  get  "admin/logout"

  resources :families do
    resources :fish
  end
  resources :fish do
    resources :photos
  end
  resources :photos
  resource :search

  # Facebook access
  scope "/fb" do
    resources :families do
      resources :fish
    end
    resources :fish do
      resources :photos
    end
    resources :photos
    resource :search
  end

  match "/admin/" => "admin#login"
  root to: "families#index"
end

app/models/fish.rb
# -*- coding: utf-8 -*-
require 'nkf'

class Fish < ActiveRecord::Base
  include NKF

  belongs_to :family
  has_many :photo
  belongs_to :thumb_photo, class_name: 'Photo'

  before_validation do |fish|
    fish.name_jp = nkf('-w --katakana', fish.name_jp) if fish.name_jp
    fish.nickname_jp = nkf('-w --katakana', fish.nickname_jp) if fish.nickname_jp
    fish.name_en = fish.name_en.capitalize
    fish.name_la = fish.name_la.capitalize
  end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  # GET /fish
  # GET /fish.json
  def index
    if params[:family_id]
      @family = Family.find(params[:family_id])
      @fish = Fish.joins(:family).where(family_id: params[:family_id]).order('families.name_jp, name_jp')
    else
      @family = nil
      @fish = Fish.joins(:family).order('families.name_jp, name_jp')
    end

    respond_to do |format|
      if admin?
        format.html # index.html.erb
      else
        format.html { render layout: 'mobile', template: 'fish/index.mobile' }
      end
      format.json { render json: @fish }
    end
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
    @fish = Fish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/new
  # GET /fish/new.json
  def new
    if params[:family_id]
      @family = Family.find(params[:family_id])
    else
      @family = nil
    end
    @fish = Fish.new
    @fish.family = @family

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/1/edit
  def edit
    if params[:family_id]
      @family = Family.find(params[:family_id])
    else
      @family = nil
    end
    @fish = Fish.find(params[:id])
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(params[:fish])

    respond_to do |format|
      if @fish.save
        format.html { redirect_to fish_path(@fish), notice: 'Fish was successfully created.' }
        format.json { render json: @fish, status: :created, location: @fish }
      else
        format.html { render action: "new" }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fish/1
  # PUT /fish/1.json
  def update
    if params[:family_id]
      @family = Family.find(params[:family_id])
    else
      @family = nil
    end
    @fish = Fish.find(params[:id])

    respond_to do |format|
      if @fish.update_attributes(params[:fish])
        format.html { redirect_to fish_path(@fish), notice: 'Fish was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish = Fish.find(params[:id])

    if @fish.family
      @family = @fish.family
    else
      @family = nil
    end

    @fish.destroy

    respond_to do |format|
      if @family
        format.html { redirect_to family_fish_index_path(@family) }
      else
        format.html { redirect_to fish_index_path }
      end
      format.json { head :ok }
    end
  end
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.haml
-if @fish.errors.any?
  #error_explanation
    %h2= "#{pluralize(@fish.errors.count, "error")} prohibited this fish from being saved:"
    %ul
      - @fish.errors.full_messages.each do |msg|
        %li= msg

= form_for(@fish) do |f|
  .field
    %table
      %tr
        %td= f.label '科'
        %td= f.collection_select(:family_id, Family.all, :id, :name_jp)
      %tr
        %td= f.label :name_jp
        %td= f.text_field :name_jp
      %tr
        %td= f.label :description_jp
        %td= f.text_area :description_jp
      %tr
        %td= f.label :nickname_jp
        %td= f.text_field :nickname_jp
      %tr
        %td= f.label :name_la
        %td= f.text_field :name_la
      %tr
        %td= f.label :name_en
        %td= f.text_field :name_en
    - if @fish.id    
      %p 代表的な写真
      %div
        - Photo.where("fish_id = #{@fish.id}").each do |photo|
          %div{ 'style' => 'float:left;' }
            = f.radio_button(:thumb_photo_id, photo.id)
            = image_tag photo.file.thumb.url, { 'style' => 'vertical-align:text-top;' }
  .actions{ 'style' => 'clear:left;' }
    = f.submit '保存'
  

app/views/fish/edit.html.haml
= content_for :header do
  %h1= @fish.name_jp

= render 'form'

app/views/fish/index.html.haml
= content_for :header do
  %h1
    - if @family
      = "#{@family.name_jp}の魚一覧"
    - else
      魚一覧
  .menu
    - if @family
      %button= link_to "#{@family.name_jp}の魚を追加", new_family_fish_path(@family)
      %button= link_to "#{@family.name_jp}の情報を編集", edit_family_path(@family)
    - else
      %button= link_to '魚を追加', new_fish_path
%table
  %tr
    %th 科
    %th 和名
    %th 学名
    %th 英名
    %th 説明
    %th.photo 代表写真
    %th.operation 操作
    %th.index 一覧
  - @fish.each do |fish|
    %tr
      %td
        -  if fish.family
          = link_to fish.family.name_jp, family_fish_index_path(fish.family)
      %td= link_to fish.name_jp, fish_photos_path(fish)
      %td= fish.name_la
      %td= fish.name_en
      %td= fish.description_jp
      - if fish.thumb_photo
        %td.photo= image_tag fish.thumb_photo.file.thumb.url
      - else
        %td.photo no photo
      %td.operation
        %button= link_to '表示', fish
        %button= link_to '編集', edit_fish_path(fish)
        %button= link_to '削除', fish, :confirm => 'まじです？', :method => :delete
      %td.index
        %button= link_to '写真', fish_photos_path(fish)

app/views/fish/index.mobile.html.haml
= content_for :header do
  %h1
    - if @family
      = "#{@family.name_jp}"
    - else
      = Fish

%ul{'data-role' => 'listview'}
  - @fish.each do |fish|
    %li
      %a{ href: fish_photos_path(fish) }
        = image_tag fish.thumb_photo.file.mobile.url if fish.thumb_photo
        %h3= fish.name_jp
        %p<
          = fish.name_la if ! fish.name_la.blank?
          = " / #{fish.name_en}" if ! fish.name_en.blank?

app/views/fish/new.html.haml
= content_for :header do
  %h1 新規（魚）
  
= render 'form'

  
  

app/views/fish/show.html.haml
= content_for :header do
  %h1= @fish.name_jp
  .menu
    %button= link_to '編集', edit_fish_path(@fish)
    %button= link_to '削除', @fish, :confirm => 'まじでまじすか？', :method => :delete
    %button= link_to "#{@fish.name_jp}の写真一覧", fish_photos_path(@fish)
    %button= link_to "#{@fish.name_jp}の写真追加", new_fish_photo_path(@fish)

- if @fish.thumb_photo
  %div.center
    = image_tag @fish.thumb_photo.file.mobile.url
%table
  %tr
    %td= t '科'
    %td= @fish.family.name_jp
  %tr
    %td= t 'activerecord.attributes.fish.name_jp'
    %td= @fish.name_jp
  %tr
    %td= t 'activerecord.attributes.fish.nickname_jp'
    %td= @fish.nickname_jp
  %tr
    %td= t 'activerecord.attributes.fish.description_jp'
    %td= @fish.description_jp
  %tr
    %td= t 'activerecord.attributes.fish.name_la'
    %td= @fish.name_la
  %tr
    %td= t 'activerecord.attributes.fish.name_en'
    %td= @fish.name_en